apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puzzle-api
  template:
    metadata:
      labels:
        app: puzzle-api
    spec:
      containers:
        - name: puzzle-api
          image: images.teknobulut.net/neon-shard-level-designer/neon-shard-level-designer:2025.6.23.2  # Docker imajını güncelle
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: "mongodb://db.teknobulut.net:27017/puzzle_db"
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
      imagePullSecrets:
        - name: harborsecret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puzzle-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ns-level-designer.teknobulut.net # Domainini güncelle
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: puzzle-api-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: puzzle-api-service
  labels:
    app: puzzle-api-service
spec:
  selector:
    app: puzzle-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP