apiVersion: apps/v1
kind: Deployment
metadata:
  name: titconn-keyvault-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titconn-keyvault
  template:
    metadata:
      labels:
        app: titconn-keyvault
    spec:
      containers:
      - name: titconn-keyvault-container
        image: harbor.teknobulut.net/titconnsisecam/titconn-keyvault:2024.2.17.26
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      imagePullSecrets:
      - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: titconn-keyvault-service
  labels:
   app: titconn-keyvault-service
spec:
  selector:
    app: titconn-keyvault
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: titconn-keyvault-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - titconn-sisecam-keyvault.teknobulut.net
      secretName: titconn-keyvault-ingress
  rules:
    - host: titconn-sisecam-keyvault.teknobulut.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titconn-keyvault-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titconn-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titconn-hub
  template:
    metadata:
      labels:
        app: titconn-hub
    spec:
      containers:
      - name: titconn-hub-container
        image: harbor.teknobulut.net/titconnsisecam/titconn-hub:2024.2.17.26
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      imagePullSecrets:
      - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: titconn-hub-service
  labels:
   app: titconn-hub-service
spec:
  selector:
    app: titconn-hub
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: titconn-hub-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - titconn-sisecam-hub.teknobulut.net
      secretName: titconn-hub-ingress
  rules:
    - host: titconn-sisecam-hub.teknobulut.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titconn-hub-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titconn-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titconn-api
  template:
    metadata:
      labels:
        app: titconn-api
    spec:
      containers:
      - name: titconn-api-container
        image: harbor.teknobulut.net/titconnsisecam/titconn-api:2024.2.17.26
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      imagePullSecrets:
      - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: titconn-api-service
  labels:
   app: titconn-api-service
spec:
  selector:
    app: titconn-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: titconn-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - titconn-sisecam-api.teknobulut.net
      secretName: titconn-api-ingress
  rules:
    - host: titconn-sisecam-api.teknobulut.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titconn-api-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titconn-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titconn-microservice
  template:
    metadata:
      labels:
        app: titconn-microservice
    spec:
      containers:
      - name: titconn-microservice-container
        image: harbor.teknobulut.net/titconnsisecam/titconn-microservice:2024.2.17.26
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      imagePullSecrets:
      - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: titconn-microservice-service
  labels:
   app: titconn-microservice-service
spec:
  selector:
    app: titconn-microservice
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: titconn-microservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - titconn-sisecam-microservice.teknobulut.net
      secretName: titconn-microservice-ingress
  rules:
    - host: titconn-sisecam-microservice.teknobulut.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titconn-microservice-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titconn-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titconn-scheduler
  template:
    metadata:
      labels:
        app: titconn-scheduler
    spec:
      containers:
      - name: titconn-scheduler-container
        image: harbor.teknobulut.net/titconnsisecam/titconn-scheduler:2024.2.17.26
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      imagePullSecrets:
      - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: titconn-scheduler-service
  labels:
   app: titconn-scheduler-service
spec:
  selector:
    app: titconn-scheduler
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: titconn-scheduler-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - titconn-sisecam-scheduler.teknobulut.net
      secretName: titconn-scheduler-ingress
  rules:
    - host: titconn-sisecam-scheduler.teknobulut.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titconn-scheduler-service
                port:
                  number: 80

