apiVersion: apps/v1
kind: Deployment
metadata:
  name: titconn-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: titconn-app
  template:
    metadata:
      labels:
        app: titconn-app
    spec:
      containers:
      - name: titconn-app-container
        image: images.teknobulut.net/titconndhlgateway/titconn-app:2024.11.15.1
        imagePullPolicy: Always
        env:
            - name: ASPNETCORE_URLS
      imagePullSecrets:
      - name: harborsecret
---
apiVersion: v1
kind: Service
metadata:
  name: titconn-app-service
  labels:
   app: titconn-app-service
spec:
  selector:
    app: titconn-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: titconn-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.dhltr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
               service:
                 name: titconn-app-service
                 port: 
                   number: 8080
